sudo: required
language: generic

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker run ubuntu:16.04 /bin/bash -c "apt-get update; apt-get upgrade -y; apt-get install -y git; git clone https://github.com/robdyke/ubuntu-defaults-image-rd.git; cd ubuntu-defaults-image-rd; ./build.sh amd64"
