sudo: required
language: generic

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker run ubuntu:16.04 /bin/sh -c "apt-get update && apt-get upgrade --yes"
  # - docker run apt-get install git --yes
  # - docker run git clone https://github.com/robdyke/ubuntu-defaults-image-rd.git
  # - docker run cd ubuntu-defaults-image-rd && ./build.sh amd64
