sudo: required
language: generic
services:
- docker
jobs:
  include:
  - stage: amd64
    script:
    - docker pull nhsbuntu/ubuntu-defaults-image:latest
    - docker run --env BUILDARCH=amd64 --env BUILDFLAVOUR=gnome --env BUILDLOG=quiet --rm -it -v `pwd`:`pwd`
      -w `pwd` --name buildamd64 --privileged nhsbuntu/ubuntu-defaults-image /bin/bash
      -c "./build.sh"
  - stage: i386
    script:
    - docker pull nhsbuntu/ubuntu-defaults-image:latest
    - docker run --env BUILDARCH=i386 --env BUILDFLAVOUR=gnome --env BUILDLOG=quiet --rm -it -v `pwd`:`pwd`
      -w `pwd` --name buildi386 --privileged nhsbuntu/ubuntu-defaults-image /bin/bash
      -c "./build.sh"
env:
  global:
  - secure: okCvUhr1r0egoZ8aPWVNLuQTHwMkrWH8BeELfml63BsUtCLED/mfqaOVQ85WLyOihnQUDTA93KGjhc5iY0cSpQGPd2cbrJVLPP35M1zYLCJIj3bIrJskAwkr1bKbp+NdWdSiJQ2URiOIZ09kjJ+4KDnHeytWMvH5X923U2fG5DgmUWuOycILJYJKPPapMAz8XHfjpcq6X8eUzaa6BYAKnfyDu878Id8NhTKDwwuwBtO72Ic3IS12kz29/ErBclVGmxTkml4TBAdUOBDUUOg9ReX36hLnP/+1fbBIfDOzNxkDmKAFGZGkVrRlbmjqai7dzqeDwAecsDUG+Sjb8eN/yd+iczZuYznz+lSE2naUvF9kKz93gy6AJHgSN3ESrWhA72Z6BoI87Ilncfd8HdpMJjr6MGYYQsAD/5ouBrBsssWlv7rfY679fmElU636lxp/+zFYIlYok4fOm+mz5ncgufN42SgddTV1sfULtZzqi8gWbB3m0wXPE0by1zmdE+i/6HzxLMCvlXpxRu4OI7ZHRqMvQaLYL9JsQ36W/CVHM+gHQtzLjAr/VhkZwAmWZYeg5/SRGTALOABgVYAMpFuVCI7SH0LFMcZtMJ2ETpR9ZFNCO+2FI73MsY+BAtWGiPu/n1Ifh9r071NhunleZdMmmGu7qv/tWQIhpLkvKphN8wI=
  - secure: V7SUhvDJBtLbQrYV+Nx2ibdyqjV54hY1Raa6RNY2pZvCm7K0mPEMjSpYNmMJZ6iBm5535x5CHCyUXFYlugFnvWVzbkh9d5QykqmUf/Vh6VMf3I28rLQsrdAx+B9/VrN9c4/W6sLmJNmxVNKGfJUf4gNRh+0kAfJttiUWQAzjt8UiVKsZGz9CtnTAZTUMC6zNtjMDhKINs1RpSy/lDArIZaTPtuaBvfHwJwvspENn+oyCedz6IUa8DH6wLfoJBGuNZqQNM2eBdKT+gRxiil5tT7bGoKrRlIshxf9XIpBm68Vy4HGan1QHV6TAreAYagLETtCWd76MloSrLDF84kzUjFeKJvKU2N6/Kikk5dzrjimgFfE3FSIpa26+WzhRqKDByhAvayGZ/pcpUoCOgP/yLbfs2wlr0aXZPtFIV+B1VBBrB6+vlTa/peiI8A2YMyYl9sakGdaS3vUHaAL9eRKV2EFUWVu8/ILyJLRekATXjUDqN87IRGSugMn9L+Q4iUo+N7ELrRGFUHLYeRc+c4rmMTLtNv2+8h9OwzxGKpeszOix6WeXEtxViQSovjRRZoQLnPgpbBrG2vqT7nLsYkB0BkxqXKTOSktRWs5WEAAy56mYVX9HSGIJVF2fYko3BbBQpfRmiRzR4QnJXBoAm8WeKey0yRnuHReuUg39g/cECRs=
after_success:
- openssl aes-256-cbc -K $encrypted_ca6ee2a377e2_key -iv $encrypted_ca6ee2a377e2_iv
  -in build_rsa.enc -out build_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 build_rsa
- ssh-add build_rsa
- scp -o stricthostkeychecking=no NHSbuntu-*-amd64*-binary* $BUILDUSER@$BUILDHOST:/mnt/ISO/amd64
- scp -o stricthostkeychecking=no NHSbuntu-*-i386*-binary* $BUILDUSER@$BUILDHOST:/mnt/ISO/i386
notifications:
  slack:
    secure: r1DhvwOVcxN7JmfBkSF389VhGGUa7UDnG/M+LcxasINe2VV2ymemaxEoVbeDF4unXtwc5xImuYQUxtLs0Q+SmIMAUl0dggv/5quw5gw9hiURdmyC6JPtgDZDPAZ4GUiRFstWhqpRW1n07hHDaSkQOmFJxpTP/mtm80BamXsKYGrW6z/PekcbmDzhfWZk1zAnJTsrNuYFA+Ii9Cv6kUbwEYKlF2axArpcQ7kvOcGY/a6YB36JVxmMmNf6zlTipUka5BUyH5HAUr4eGOwiZ3Flba55/SxDPzFcWO7reLreypjeM471qFpTVOnXmaKH7G3lFunPGu/LIX2hSIUjnrM1E51cNBPeI6cfExoOsH9p0lvDtu191kHnRjWDKyTEJLmmfR5Ibe4UcsYIMxUfE1jNrks1qLxvwKHVBVeFP76RohyzJfg+x/cMQMay76l2TR2+NihaBxoZH+Wjx+2OPvhdVZzyPPWhY/iiSxORlkP7Ad4XMj4FLgbY3fLjvKmaOC+AO8h5i/ZFSoXJ4vCOSFbLFpjAR8dOp8tYAofMDjriT4zXN90Z/+oPRmA8djkEcMXmdMZAHd6hbAd+KK2MwzOHaBAqpmHZKs0gx2tUtJwAc6XKL3RhBq9GIel0IwGnRf4v9xQ3bcMZLUMeAVq/r7f9bQMXyTXI7jVmMLCw5xWEs/g=
