sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ubuntu-defaults-image-rd .
  - docker run --privileged ubuntu-defaults-image-rd /bin/sh -c "cd /ubuntu-defaults-image-rd; ./build-amd64.sh"
